// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gpbbpwnhmxxewaddlwxs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdwYmJwd25obXh4ZXdhZGRsd3hzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzOTAwNzksImV4cCI6MjA2OTk2NjA3OX0.Dod6CCo0yj_sZF0YKxP8V6aNLhxMnjXM3ISKFJ6k6Ig";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});